### ISSUE TITLE
Replace built-in Jinja2 support with Jinja2 processor

### ISSUE THREAD

**Issue by ikalnytskyi** [ikalnytskyi/holocron#8]
Holocron support processors pipeline now, which means any transformation or modification applied to documents can be and should be expressed via processors. Unfortunately, we are not there with Jinja2. We use Jinja2 templates not only for documents but for virtual documents (see `index` and `tags` processors). That means we have *implicit* dependency on it.

We need to find a way to workaround this issue, so using any template engine for Holocron won't be an issue.

**Comment by ikalnitsky** [comment]
@rultor hello
